--- #YAML:1.0
name:               TX
version:            0.08
abstract:           a simple template system based on Text::Template::Library
author:
    - Torsten Foertsch <torsten.foertsch@gmx.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Text::Template::Library:  0.02
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
